# Generated by Django 5.1.4 on 2024-12-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_produto_percentual_comissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comissao",
            name="percentual_maximo",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name="comissao",
            name="percentual_minimo",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name="produto",
            name="percentual_comissao",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
